name: cwl
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.18+23 #2.1.11+16

# test p ---

# flutter build apk --release
# flutter build appbundle --release

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # for handling permissions
  permission_handler: ^5.0.0+hotfix.4
  # for Icons
  font_awesome_flutter: ^8.8.1
  # for Progress dialog
  progress_dialog: ^1.2.1
  # For local data storage
  shared_preferences: ^0.5.6+3
  # For rendom string generation
  uuid: ^2.0.4
  # For Encryption
  encrypt: ^4.0.0
  # http request
  http: ^0.12.0+4
  # for auto model creation
  json_annotation:
  # async package to add additional Cancellable operations
  async: ^2.4.0
  # get it
  get_it: ^3.0.0+1
  # provider
  provider: ^4.0.1
  # provider architecture
  provider_architecture: ^1.0.6
  # for getting app version details
  package_info: ^0.4.0+16
  # For internationalization and localization facilities
  intl: ^0.16.1
  # For autocomplete textinput
  autocomplete_textfield: ^1.7.3
  # for location
  geolocator: ^5.3.1
  # for barcodescanner
  flutter_barcode_scanner: ^1.0.0
  # for image picker
  image_picker: ^0.6.6+1
  # for image croping and rotate
  image_cropper: ^1.2.2
  # for image compress
  flutter_image_compress: ^0.6.8
  # for lunching url
  url_launcher: ^5.4.10
  # For Bacode Scan
  barcode_scan: ^1.0.0
  # For PDF View
  native_pdf_view: ^3.6.2
  flutter_pdfview: ^1.0.0+10
  # File Share
  esys_flutter_share: ^1.0.2
  # Back Button Press MSG
  fluttertoast: ^7.0.2
  #firebase Notification Massaging
  firebase_messaging: ^6.0.16
  # Animetion 
  simple_animations: ^1.3.3
  # Group Button CheckBox
  grouped_buttons: ^1.0.4
  # Firebase Auth Login 
  firebase_auth: 
  # Popup Menu 
  rflutter_alert: ^1.0.3
  # Google Map
  google_maps_flutter: 
  # Address From LatLong 
  geocoding: ^1.0.5
  flutter_svg: ^0.19.1

  
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.6
  cached_network_image: 2.0.0-rc.1
  flutter_local_notifications: 1.4.0
  photo_view: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_model:
  json_serializable:
  #flutter packages pub run json_model

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - CWL-LOGO.png
    - home_image.jpg
    - loader.gif
    - map-img.jpg
    - app-background.jpg
    - assets/images/background.png
    - assets/images/background-2.png
    - assets/images/waybill-background.jpg
    - assets/images/trip-update-background.jpg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
